# Generated by Django 2.2.6 on 2019-11-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('restaurant_id', models.TextField(db_column='Restaurant ID', primary_key=True, serialize=False)),
                ('restaurant_name', models.TextField(blank=True, db_column='Restaurant Name', null=True)),
                ('cuisines', models.TextField(blank=True, db_column='Cuisines', null=True)),
                ('average_cost_for_two', models.TextField(blank=True, db_column='Average Cost for two', null=True)),
                ('currency', models.TextField(blank=True, db_column='Currency', null=True)),
                ('has_table_booking', models.TextField(blank=True, db_column='Has Table booking', null=True)),
                ('has_online_delivery', models.TextField(blank=True, db_column='Has Online delivery', null=True)),
                ('aggregate_rating', models.TextField(blank=True, db_column='Aggregate rating', null=True)),
                ('rating_color', models.TextField(blank=True, db_column='Rating color', null=True)),
                ('rating_text', models.TextField(blank=True, db_column='Rating text', null=True)),
                ('votes', models.TextField(blank=True, db_column='Votes', null=True)),
            ],
            options={
                'db_table': 'restaurants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantsLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.TextField(blank=True, db_column='Country Code', null=True)),
                ('city', models.TextField(blank=True, db_column='City', null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('locality', models.TextField(blank=True, db_column='Locality', null=True)),
                ('locality_verbose', models.TextField(blank=True, db_column='Locality Verbose', null=True)),
                ('longitude', models.TextField(blank=True, db_column='Longitude', null=True)),
                ('latitude', models.TextField(blank=True, db_column='Latitude', null=True)),
            ],
            options={
                'db_table': 'restaurants_location',
                'managed': False,
            },
        ),
    ]
